name: Production Grid Demo
root_tenant_host: productiongrid.com
port: 8000
database:
  primary:
    hostname: localhost
    port: 5432
    schema: pgrid_core
    user: pgrid
    password: pgrid
  replica:
    hostname: localhost
    port: 5432
    schema: pgrid_core
    user: pgrid
    password: pgrid
