package applications

/*
CrudResourceMetaData models metadata about a specific domain and is used
for autogenerated CRUD user interface screens in the Vue.js UI.
*/
type CrudResourceMetaData struct {
	ListPageTitle      string `json:"listPageTitle"`
	ListPageHelp       string `json:"listPageHelp"`
	NewFormTitle       string `json:"newFormTitle"`
	NewFormHelp        string `json:"newFormHelp"`
	EmptyListCaption   string `json:"emptyListCaption"`
	EditFormTitle      string `json:"editFormTitle"`
	EditFormHelp       string `json:"editFormHelp"`
	ResourceName       string `json:"resourceName"`
	ResourceNamePlural string `json:"resourceNamePlural"`
	DeletePrompt       string `json:"deletePrompt"`
	NewDisabled        bool   `json:"newDisabled"`
	DeleteEnabled      bool   `json:"deleteEnabled"`
	SearchEnabled      bool   `json:"searchEnabled"`

	Columns []CrudField `json:"columns"`
	Fields  []CrudField `json:"fields"`
	Tabs    []CrudTab   `json:"tabs"`
}

/*
CrudField models a field on a data entry form.
*/
type CrudField struct {
	ID            string `json:"id"`
	Caption       string `json:"caption"`
	Help          string `json:"help"`
	Tab           string `json:"tab"`
	DataType      string `json:"dataType"`
	Required      bool   `json:"required"`
	DisplayOnForm bool   `json:"displayOnForm"`
	Min           int    `json:"min"`
	Max           int    `json:"max"`
	Mutable       bool   `json:"mutable"`
	HideIfEmpty   bool   `json:"hideIfEmpty"`
	ColumnStyle   string `json:"columnStyle"`
}

// CrudFieldSet contains a group of fields.
type CrudFieldSet struct {
	ID      string      `json:"id"`
	Caption string      `json:"caption"`
	Fields  []CrudField `json:"fields"`
}

/*
CrudTab models a tab on a crud data entry form.
*/
type CrudTab struct {
	ID        string         `json:"id"`
	Caption   string         `json:"caption"`
	Fields    []CrudField    `json:"fields"`
	FieldSets []CrudFieldSet `json:"fieldsets"`
}

/*
NewCrudMetaData is a factory function that creates a blank instance of
CrudResourceMetaData with the slices initialized.
*/
func NewCrudMetaData() CrudResourceMetaData {
	return CrudResourceMetaData{
		Columns: make([]CrudField, 0),
		Fields:  make([]CrudField, 0),
		Tabs:    make([]CrudTab, 0)}
}

/*
WithField adds a field to crud resource meta data.  Used for flat forms without tabs.
*/
func (md *CrudResourceMetaData) WithField(field CrudField) *CrudResourceMetaData {
	md.Fields = append(md.Fields, field)
	return md
}

/*
WithColumn adds a column to crud resource metadata.
*/
func (md *CrudResourceMetaData) WithColumn(field CrudField) *CrudResourceMetaData {
	md.Columns = append(md.Columns, field)
	return md
}

/*
WithTab adds a tab to crud resource metad data.
*/
func (md *CrudResourceMetaData) WithTab(tab CrudTab) *CrudResourceMetaData {
	md.Tabs = append(md.Tabs, tab)
	return md
}

/*
WithField adds a field to a crud resource tab.
*/
func (tab *CrudTab) WithField(field CrudField) *CrudTab {
	tab.Fields = append(tab.Fields, field)
	return tab
}
